version: 2
jobs:
  build:
    working_directory: ~/kronostechnologies/oauth2-providers
    parallelism: 1
    shell: /bin/sh --login

    docker:
    - image: php:5.6-cli-alpine
      command: /sbin/init

    steps:
    - checkout
    - run: chmod u+x ./.circleci/scripts/bootstrap.sh && ./.circleci/scripts/bootstrap.sh
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: /composer/composer.phar install --no-interaction
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
    - run: ./vendor/bin/phpunit
