version: 2
aliases:
  # Variables
  - &composer_install_cache_key v5-composer-install-{{ checksum "composer.lock" }}

jobs:
  phpunit-7-2:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - *composer_install_cache_key
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          paths:
            - ./vendor
          key: *composer_install_cache_key
      - run: sudo pecl install pcov
      - run:
          name: "phpunit"
          command: php -d pcov.enabled=1 -d pcov.directory=. ./vendor/bin/phpunit --coverage-clover ~/php-test-coverage.xml --log-junit ~/test-results/phpunit/junit.xml
      - store_test_results:
          path: '~/test-results'
      - store_artifacts:
          path: '~/php-test-coverage.xml'
          destination: 'php-test-coverage.clover.xml'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - phpunit-7-2
