name: PHP Security

on:
  push:
    branches:
      - master

jobs:
  php-security:
    uses: equisoft-actions/php-workflows/.github/workflows/php-security.yml@v3
    with:
      publish-reports: true
      php-version: '8.1'
      extensions: pcov
    secrets:
      GPR_KEY: ${{ secrets.GPR_KEY }}
